config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  get 'welcome/index'

  resources :midlemes
  resources :locations
  resources :users
  
end

app/models/location.rb
class Location < ActiveRecord::Base
	
	belongs_to :user
	belongs_to :midleme

	# app/models/location.rb
	geocoded_by :address
	after_validation :geocode

	
end

app/models/midleme.rb
class Midleme < ActiveRecord::Base

	belongs_to :user
	has_many :locations

	# app/models/midleme.rb
	geocoded_by :address
	after_validation :geocode

end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :locations
	has_many :midlemes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end
   
    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city, :state, :country, :address)
    end
end

app/controllers/midlemes_controller.rb
class MidlemesController < ApplicationController
  before_action :set_midleme, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 20, :order => :distance)
    else
      @locations = Location.all
    end
  end

  # GET /midlemes
  # GET /midlemes.json
  def index
    @midlemes = Midleme.all
  end

  # GET /midlemes/1
  # GET /midlemes/1.json
  def show
  end

  # GET /midlemes/new
  def new
    @midleme = Midleme.new
  end

  # GET /midlemes/1/edit
  def edit
  end

  # POST /midlemes
  # POST /midlemes.json
  def create
    @midleme = Midleme.new(midleme_params)

    respond_to do |format|
      if @midleme.save
        format.html { redirect_to @midleme, notice: 'Midleme was successfully created.' }
        format.json { render :show, status: :created, location: @midleme }
      else
        format.html { render :new }
        format.json { render json: @midleme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /midlemes/1
  # PATCH/PUT /midlemes/1.json
  def update
    respond_to do |format|
      if @midleme.update(midleme_params)
        format.html { redirect_to @midleme, notice: 'Midleme was successfully updated.' }
        format.json { render :show, status: :ok, location: @midleme }
      else
        format.html { render :edit }
        format.json { render json: @midleme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /midlemes/1
  # DELETE /midlemes/1.json
  def destroy
    @midleme.destroy
    respond_to do |format|
      format.html { redirect_to midlemes_url, notice: 'Midleme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_midleme
      @midleme = Midleme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def midleme_params
      params.require(:midleme).permit(:location_id, :latitude, :longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def index
		
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/midlemes_helper.rb
module MidlemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MidleMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <script type="text/javascript"
   src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBzgEie2Tk26CM31w2oE4LO8NvvzgbAYVQ">
  </script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Locations, Locations, Locations</h2>
<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.city %></td>
        <td><%= location.state %></td>
        <td><%= location.country %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>
<%= link_to 'New Midleme', new_midleme_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @location.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @location.country %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/midlemes/_form.html.erb
<%= form_for(@midleme) do |f| %>
  <% if @midleme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@midleme.errors.count, "error") %> prohibited this midleme from being saved:</h2>

      <ul>
      <% @midleme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/midlemes/edit.html.erb
<h1>Editing Midleme</h1>

<%= render 'form' %>

<%= link_to 'Show', @midleme %> |
<%= link_to 'Back', midlemes_path %>

app/views/midlemes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Midlemes</h1>

<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @midlemes.each do |midleme| %>
      <tr>
        <td><%= midleme.location_id %></td>
        <td><%= midleme.latitude %></td>
        <td><%= midleme.longitude %></td>
        <td><%= link_to 'Show', midleme %></td>
        <td><%= link_to 'Edit', edit_midleme_path(midleme) %></td>
        <td><%= link_to 'Destroy', midleme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Midleme', new_midleme_path %>
<%= link_to 'New Location', new_location_path %>

app/views/midlemes/new.html.erb
<h1>New Midleme</h1>

<%= render 'form' %>

<%= link_to 'Back', midlemes_path %>

app/views/midlemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @midleme.location_id %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @midleme.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @midleme.longitude %>
</p>



<%= link_to 'Edit', edit_midleme_path(@midleme) %> |
<%= link_to 'Back', midlemes_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to MidleMe</h1>
<p>We are here to help you Meet!</p>

<ul>
	<li>Enter your Location</li>
	<li>Add location of whom you're meeting</li>
	<li>We'll find the point in the Midle</li>
</ul>

<%= image_tag('MapLook.jpg') %>

<%= link_to 'MidleMe', midlemes_path %>
<%= link_to 'New Location', new_location_path %>

<!-- Display one marker -->
<div id="map-canvas"></div>  

<!-- Display multiple markers -->
<!-- <div id="map_wrapper">
    <div id="map_canvas" class="mapping"></div>
</div>